from enum import Enum

from pydantic import Field, field_validator, model_validator

from ..base import FrigateBaseModel
from ..env import EnvString
from .objects import DEFAULT_TRACKED_OBJECTS

__all__ = ["OnvifConfig", "PtzAutotrackConfig", "ZoomingModeEnum"]


class ZoomingModeEnum(str, Enum):
    disabled = "disabled"
    absolute = "absolute"
    relative = "relative"
    continuous = "continuous"


class PtzAutotrackConfig(FrigateBaseModel):
    enabled: bool = Field(
        default=False,
        title="Enable Autotracking",
        description="Enable or disable automatic PTZ camera tracking of detected objects.",
    )
    calibrate_on_startup: bool = Field(
        default=False,
        title="Calibrate on start",
        description="Measure PTZ motor speeds on startup to improve tracking accuracy. Frigate will update config with movement_weights after calibration.",
    )
    zooming: ZoomingModeEnum = Field(
        default=ZoomingModeEnum.disabled,
        title="Zoom mode",
        description="Control zoom behavior: disabled (pan/tilt only), absolute (most compatible), relative (concurrent pan/tilt/zoom), or continuous (velocity-based zoom for cameras without position control).",
    )
    zoom_factor: float = Field(
        default=0.3,
        title="Zoom factor",
        description="Control zoom level on tracked objects. Lower values keep more scene in view; higher values zoom in closer but may lose tracking. Values between 0.1 and 0.75.",
        ge=0.1,
        le=0.75,
    )
    track: list[str] = Field(
        default=DEFAULT_TRACKED_OBJECTS,
        title="Tracked objects",
        description="List of object types that should trigger autotracking.",
    )
    required_zones: list[str] = Field(
        default_factory=list,
        title="Required zones",
        description="Objects must enter one of these zones before autotracking begins.",
    )
    return_preset: str = Field(
        default="home",
        title="Return preset",
        description="ONVIF preset name configured in camera firmware to return to after tracking ends.",
    )
    timeout: int = Field(
        default=10,
        title="Return timeout",
        description="Wait this many seconds after losing tracking before returning camera to preset position.",
    )
    continuous_speed: float = Field(
        default=2.0,
        title="Continuous move speed",
        description="FOV units the camera traverses per second at velocity 1.0 for ContinuousMove PTZ cameras. Higher values mean faster movement. Typical range: 0.5-4.0.",
        ge=0.1,
        le=10.0,
    )
    continuous_zoom_speed: float = Field(
        default=1.0,
        title="Continuous zoom speed",
        description="Zoom units per second at velocity 1.0 for ContinuousMove PTZ cameras. Lower values mean slower, more precise zoom. Typical range: 0.5-2.0.",
        ge=0.1,
        le=5.0,
    )
    assumed_zoom_range: tuple[float, float] | None = Field(
        default=None,
        title="Assumed zoom range",
        description="Zoom range in the camera's native units (as shown on the OSD) for cameras that do not report zoom position. Example: [1, 30] for a 30x optical zoom camera.",
    )
    preset_zoom_level: float | None = Field(
        default=None,
        title="Preset zoom level",
        description="Zoom level at the return preset in the camera's native units, for cameras that do not report zoom position. Example: 10 for a preset at 10x optical zoom.",
    )
    movement_weights: str | list[str] | None = Field(
        default_factory=list,
        title="Movement weights",
        description="Calibration values automatically generated by camera calibration. Do not modify manually.",
    )
    enabled_in_config: bool | None = Field(
        default=None,
        title="Original autotrack state",
        description="Internal field to track whether autotracking was enabled in configuration.",
    )

    @field_validator("assumed_zoom_range", mode="before")
    @classmethod
    def validate_zoom_range(cls, v):
        if v is None:
            return None

        if isinstance(v, (list, tuple)) and len(v) == 2:
            min_val, max_val = v
            if isinstance(min_val, (int, float)) and isinstance(max_val, (int, float)):
                if min_val > 0 and min_val < max_val:
                    return (float(min_val), float(max_val))
                else:
                    raise ValueError(
                        "assumed_zoom_range values must be positive with min < max (e.g., [1, 30] for 1x-30x zoom)"
                    )

        raise ValueError(
            "assumed_zoom_range must be a tuple of two numbers representing min and max zoom in camera units"
        )

    @model_validator(mode="after")
    def validate_preset_within_range(self):
        """Validate that preset_zoom_level is within assumed_zoom_range if both are set."""
        if self.preset_zoom_level is not None and self.assumed_zoom_range is not None:
            min_zoom, max_zoom = self.assumed_zoom_range
            if not (min_zoom <= self.preset_zoom_level <= max_zoom):
                raise ValueError(
                    f"preset_zoom_level ({self.preset_zoom_level}) must be within "
                    f"assumed_zoom_range ({min_zoom}, {max_zoom})"
                )
        return self

    @field_validator("movement_weights", mode="before")
    @classmethod
    def validate_weights(cls, v):
        if v is None:
            return None

        if isinstance(v, str):
            weights = list(map(str, map(float, v.split(","))))
        elif isinstance(v, list):
            weights = [str(float(val)) for val in v]
        else:
            raise ValueError("Invalid type for movement_weights")

        if len(weights) != 6:
            raise ValueError(
                "movement_weights must have exactly 6 floats, remove this line from your config and run autotracking calibration"
            )

        return weights


class OnvifConfig(FrigateBaseModel):
    host: EnvString = Field(
        default="",
        title="ONVIF host",
        description="Host (and optional scheme) for the ONVIF service for this camera.",
    )
    port: int = Field(
        default=8000,
        title="ONVIF port",
        description="Port number for the ONVIF service.",
    )
    user: EnvString | None = Field(
        default=None,
        title="ONVIF username",
        description="Username for ONVIF authentication; some devices require admin user for ONVIF.",
    )
    password: EnvString | None = Field(
        default=None,
        title="ONVIF password",
        description="Password for ONVIF authentication.",
    )
    tls_insecure: bool = Field(
        default=False,
        title="Disable TLS verify",
        description="Skip TLS verification and disable digest auth for ONVIF (unsafe; use in safe networks only).",
    )
    profile: str | None = Field(
        default=None,
        title="ONVIF profile",
        description="Specific ONVIF media profile to use for PTZ control, matched by token or name. If not set, the first profile with valid PTZ configuration is selected automatically.",
    )
    autotracking: PtzAutotrackConfig = Field(
        default_factory=PtzAutotrackConfig,
        title="Autotracking",
        description="Automatically track moving objects and keep them centered in the frame using PTZ camera movements.",
    )
    ignore_time_mismatch: bool = Field(
        default=False,
        title="Ignore time mismatch",
        description="Ignore time synchronization differences between camera and Frigate server for ONVIF communication.",
    )
    sunba_quirks: bool = Field(
        default=False,
        title="Sunba quirks",
        description="Enable Sunba camera compatibility workarounds for its broken PTZ implementation (swapped pan/tilt speeds, unreliable move status, separate zoom commands).",
    )
